version: '3'

services:
  recomendationeng:
    container_name: recomendation_eng
    build: recomendation_eng
    volumes:
      - ./recomendation_eng:/recomendation_eng/
    restart: always
  
  service2:
    container_name: template_service2
    build: service2
    volumes:
      - ./service2:/service2/
    restart: always
  
  auth:
    container_name: authservice
    build: auth_service
    ports:
      - "8001:8000"
    volumes:
      - ./auth_service:/auth_service/
    restart: always
  
  notification:
    container_name: notification_service
    build: notification_service
    volumes:
      - ./notification_service:/notification_service/
    restart: always